permalink: /:categories/:title/
exclude:
  - README.wiki
  - Capfile
  - config

url: http://hyip.github.io/info
name: The HYIP Project
disqus_shortname: restcookbook

google_analytics: UA-53222355-1
